#!/usr/bin/env bash
# Local-dev orchestration script for the NFT Marketplace miniapp.
#
# What it does:
#  1. Starts a fresh anvil node on port 8545 (background).
#  2. Deploys Edition + EditionsFactory + MockERC20 via forge script.
#  3. Reads the deployed addresses out of deployments/local.json.
#  4. Writes .env.local for Vite with the addresses + a dev wallet PK.
#  5. Starts vite dev on port 5184.
#
# Caveats:
#  - The buy flow (build-payment / settle) does NOT work locally because it
#    depends on the Circles indexer + the wrapped-CRC payment route. The
#    mint, list, delist, my-collection, gallery, and my-wall flows DO work.
#  - This script kills the anvil process on Ctrl-C via a trap.

set -euo pipefail

# Anvil's well-known accounts. NOT for any kind of mainnet use.
DEPLOYER_PK="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
DEPLOYER_ADDR="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
OPERATOR_PK="0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
OPERATOR_ADDR="0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
SELLER_PK="0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
SELLER_ADDR="0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE"

cleanup() {
  echo
  echo "Stopping anvil..."
  [[ -n "${ANVIL_PID:-}" ]] && kill "$ANVIL_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo "==> Starting anvil on :8545..."
anvil --port 8545 --chain-id 31337 > /tmp/anvil.log 2>&1 &
ANVIL_PID=$!
# Give anvil a moment to bind.
for i in {1..15}; do
  if curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:8545 \
    -H 'content-type: application/json' \
    -d '{"jsonrpc":"2.0","id":1,"method":"web3_clientVersion"}' | grep -q 200; then
    break
  fi
  sleep 0.4
done

echo "==> Deploying contracts via forge script..."
cd contracts
DEPLOYER_PRIVATE_KEY="$DEPLOYER_PK" OPERATOR_ADDRESS="$OPERATOR_ADDR" \
  forge script script/DeployLocal.s.sol \
  --rpc-url http://localhost:8545 \
  --broadcast \
  --silent

DEPLOYMENT="$HERE/contracts/deployments/local.json"
if [[ ! -f "$DEPLOYMENT" ]]; then
  echo "ERROR: contracts/deployments/local.json was not written"
  exit 1
fi

FACTORY=$(grep '"factory"' "$DEPLOYMENT" | sed -E 's/.*"(0x[a-fA-F0-9]+)".*/\1/')
WRAPPED=$(grep '"wrappedCrc"' "$DEPLOYMENT" | sed -E 's/.*"(0x[a-fA-F0-9]+)".*/\1/')
DEPLOY_BLOCK=$(grep '"deployBlock"' "$DEPLOYMENT" | sed -E 's/.*: ([0-9]+).*/\1/')

cd "$HERE"
cat > .env.local <<EOF
# Auto-generated by scripts/dev-local.sh - safe to delete.
VITE_FACTORY_ADDRESS=$FACTORY
VITE_DEPLOY_BLOCK=$DEPLOY_BLOCK
VITE_WRAPPED_CRC_ADDRESS=$WRAPPED
VITE_GNOSIS_RPC_URL=http://localhost:8545
VITE_DEV_WALLET_PK=$SELLER_PK
EOF

echo
echo "==> Local setup complete:"
echo "    Factory:        $FACTORY"
echo "    Mock s-gCRC:    $WRAPPED"
echo "    Deploy block:   $DEPLOY_BLOCK"
echo "    Dev wallet:     $SELLER_ADDR (anvil account #2)"
echo "    Operator:       $OPERATOR_ADDR (anvil account #1)"
echo
echo "==> Starting vite dev (Ctrl-C to stop everything)..."
npm run dev
